// The MIT License (MIT)
// 
// Copyright (c) 2014-2017, Institute for Software & Systems Engineering
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

namespace SafetySharp.Analysis
{
	using System.IO;
	using System.Linq;
	using ISSE.SafetyChecking;
	using ISSE.SafetyChecking.MarkovDecisionProcess.Unoptimized;
	using ISSE.SafetyChecking.AnalysisModel;
	using ISSE.SafetyChecking.AnalysisModelTraverser;
	using ISSE.SafetyChecking.DiscreteTimeMarkovChain;
	using ISSE.SafetyChecking.ExecutableModel;
	using ISSE.SafetyChecking.FaultMinimalKripkeStructure;
	using ISSE.SafetyChecking.Formula;
	using ISSE.SafetyChecking.MarkovDecisionProcess;
	using ISSE.SafetyChecking.Modeling;
	using ISSE.SafetyChecking.Utilities;
	using Modeling;
	using Runtime;

	public class SafetySharpInvariantAnalysisResult : InvariantAnalysisResult
	{
		/// <summary>
		///   Gets the counter example that has been generated by the model checker, if any.
		/// </summary>
		public ExecutableCounterExample<SafetySharpRuntimeModel> ExecutableCounterExample { get; internal set; }

		public static SafetySharpInvariantAnalysisResult FromInvariantAnalysisResult(InvariantAnalysisResult result, CoupledExecutableModelCreator<SafetySharpRuntimeModel> modelCreator)
		{
			var executableModel = modelCreator?.Create(0);
			var executableCounterExample = executableModel!=null && result.CounterExample!=null
				? new ExecutableCounterExample<SafetySharpRuntimeModel>(executableModel, result.CounterExample)
				: null;
			var enhancedResult = new SafetySharpInvariantAnalysisResult
			{
				CounterExample = result.CounterExample,
				ExecutableCounterExample = executableCounterExample,
				FormulaHolds = result.FormulaHolds,
				StateCount = result.StateCount,
				TransitionCount = result.TransitionCount,
				ComputedTransitionCount = result.TransitionCount,
				LevelCount = result.LevelCount,
			};
			return enhancedResult;
		}
	}

	/// <summary>
	///   Provides convienent methods for model checking S# models.
	/// </summary>
	public static class SafetySharpModelChecker
	{
		public static bool _convertNmdpToMdp = false;

		public static AnalysisConfiguration TraversalConfiguration { get; set; } = AnalysisConfiguration.Default;
		

		/// <summary>
		///   Checks whether the <paramref name="formula" /> holds in all states of the <paramref name="model" />. The appropriate model
		///   checker is chosen automatically.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="formula">The formula that should be checked.</param>
		public static SafetySharpInvariantAnalysisResult Check(ModelBase model, Formula formula)
		{
			var createModel = SafetySharpRuntimeModel.CreateExecutedModelCreator(model, formula);
			var result = new LtsMin().Check(createModel, formula);

			return SafetySharpInvariantAnalysisResult.FromInvariantAnalysisResult(result, createModel);
		}

		/// <summary>
		///   Checks whether the <paramref name="invariant" /> holds in all states of the <paramref name="model" />. The appropriate
		///   model checker is chosen automatically.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="invariant">The invariant that should be checked.</param>
		public static SafetySharpInvariantAnalysisResult CheckInvariant(ModelBase model, Formula invariant)
		{
			var createModel = SafetySharpRuntimeModel.CreateExecutedModelCreator(model, invariant);
			var qualitativeChecker = new QualitativeChecker<SafetySharpRuntimeModel>(createModel) { Configuration = TraversalConfiguration };
			var result = qualitativeChecker.CheckInvariant(formulaIndex:0);
			return SafetySharpInvariantAnalysisResult.FromInvariantAnalysisResult(result, createModel);
		}

		/// <summary>
		///   Checks whether the <paramref name="invariants" /> hold in all states of the <paramref name="model" />. The appropriate
		///   model checker is chosen automatically.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="invariants">The invariants that should be checked.</param>
		public static SafetySharpInvariantAnalysisResult[] CheckInvariants(ModelBase model, params Formula[] invariants)
		{
			var createModel = SafetySharpRuntimeModel.CreateExecutedModelCreator(model, invariants);
			var qualitativeChecker = new QualitativeChecker<SafetySharpRuntimeModel>(createModel) { Configuration = TraversalConfiguration };
			var results = qualitativeChecker.CheckInvariants(invariants);
			var newResults = results.Select(result => SafetySharpInvariantAnalysisResult.FromInvariantAnalysisResult(result, createModel));
			return newResults.ToArray();
		}

		/// <summary>
		///   Calculates the probability to reach a state where <paramref name="stateFormula" /> holds.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="stateFormula">The state formula to be checked.</param>
		public static Probability CalculateProbabilityToReachState(ModelBase model, Formula stateFormula)
		{
			Probability probabilityToReachState;

			var probabilityToReachStateFormula = new UnaryFormula(stateFormula,UnaryOperator.Finally);

			var createModel = SafetySharpRuntimeModel.CreateExecutedModelFromFormulasCreator(model);
			
			var markovChainGenerator = new DtmcFromExecutableModelGenerator<SafetySharpRuntimeModel>(createModel) { Configuration = TraversalConfiguration };
			markovChainGenerator.AddFormulaToCheck(probabilityToReachStateFormula);
			var markovChain=markovChainGenerator.GenerateMarkovChain(stateFormula);
			using (var modelChecker = new BuiltinDtmcModelChecker(markovChain, System.Console.Out))
			{
				probabilityToReachState = modelChecker.CalculateProbability(probabilityToReachStateFormula);
			}
			return probabilityToReachState;
		}

		/// <summary>
		///   Calculates the probability of formula.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="formula">The state formula to be checked.</param>
		/// <param name="terminateEarlyFormula">When terminateEarlyFormula is satisfied stop building the state space.</param>
		/// <param name="bound">The maximal number of steps. If stateFormula is satisfied the first time any step later than bound, this probability does not count into the end result.</param>
		public static Probability CalculateProbabilityOfFormulaBounded(ModelBase model, Formula formula, Formula terminateEarlyFormula, int bound)
		{
			Probability probability;

			var createModel = SafetySharpRuntimeModel.CreateExecutedModelFromFormulasCreator(model);

			var markovChainGenerator = new DtmcFromExecutableModelGenerator<SafetySharpRuntimeModel>(createModel) { Configuration = TraversalConfiguration };
			markovChainGenerator.Configuration.SuccessorCapacity *= 2;
			markovChainGenerator.AddFormulaToCheck(formula);
			var markovChain = markovChainGenerator.GenerateMarkovChain(terminateEarlyFormula);
			using (var modelChecker = new BuiltinDtmcModelChecker(markovChain, System.Console.Out))
			{
				probability = modelChecker.CalculateProbability(formula);
			}
			return probability;
		}

		/// <summary>
		///   Calculates the probability to reach a state where <paramref name="stateFormula" /> holds.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="stateFormula">The state formula to be checked.</param>
		/// <param name="bound">The maximal number of steps. If stateFormula is satisfied the first time any step later than bound, this probability does not count into the end result.</param>
		public static Probability CalculateProbabilityToReachStateBounded(ModelBase model, Formula stateFormula, int bound)
		{
			var formula = new BoundedUnaryFormula(stateFormula, UnaryOperator.Finally, bound);

			return CalculateProbabilityOfFormulaBounded(model, formula, stateFormula, bound);
		}

		/// <summary>
		///   Calculates the probability to reach a state where <paramref name="stateFormula" /> holds and on its way
		///   invariantFormula holds in every state, or more formally Pr[invariantFormula U stateFormula].
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="stateFormula">The state formula which _must_ finally be true.</param>
		/// <param name="invariantFormula">The state formulas which must hold until stateFormula is satisfied.</param>
		/// <param name="bound">The maximal number of steps. If stateFormula is satisfied the first time any step later than bound, this probability does not count into the end result.</param>
		public static Probability CalculateProbabilityToReachStateBounded(ModelBase model, Formula stateFormula, Formula invariantFormula, int bound)
		{
			var formula = new BoundedBinaryFormula(invariantFormula, BinaryOperator.Until, stateFormula, bound);
			
			return CalculateProbabilityOfFormulaBounded(model, formula, stateFormula, bound);
		}

		/// <summary>
		///   Calculates the probability to reach a state where <paramref name="stateFormula" /> holds.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="stateFormula">The state formula which _must_ finally be true.</param>
		public static ProbabilityRange CalculateProbabilityRangeToReachState(ModelBase model, Formula stateFormula)
		{
			ProbabilityRange probabilityRangeToReachState;

			var probabilityToReachStateFormula = new UnaryFormula(stateFormula, UnaryOperator.Finally);

			var createModel = SafetySharpRuntimeModel.CreateExecutedModelFromFormulasCreator(model);

			var nmdpGenerator = new NmdpFromExecutableModelGenerator<SafetySharpRuntimeModel>(createModel) { Configuration = TraversalConfiguration };
			nmdpGenerator.AddFormulaToCheck(probabilityToReachStateFormula);
			nmdpGenerator.Configuration.SuccessorCapacity *= 8;
			var nmdp = nmdpGenerator.GenerateMarkovDecisionProcess(stateFormula);

			if (_convertNmdpToMdp)
			{
				var nmdpToMpd = new NmdpToMdp(nmdp);
				var mdp = nmdpToMpd.MarkovDecisionProcess;
				using (var modelChecker = new BuiltinMdpModelChecker(mdp, System.Console.Out))
				{
					probabilityRangeToReachState = modelChecker.CalculateProbabilityRange(probabilityToReachStateFormula);
				}
			}
			else
			{
				using (var modelChecker = new BuiltinNmdpModelChecker(nmdp, System.Console.Out))
				{
					probabilityRangeToReachState = modelChecker.CalculateProbabilityRange(probabilityToReachStateFormula);
				}
			}

			return probabilityRangeToReachState;
		}



		/// <summary>
		///   Calculates the probability of formula.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="formula">The state formula to be checked.</param>
		/// <param name="terminateEarlyFormula">When terminateEarlyFormula is satisfied stop building the state space.</param>
		/// <param name="bound">The maximal number of steps. If stateFormula is satisfied the first time any step later than bound, this probability does not count into the end result.</param>
		public static ProbabilityRange CalculateProbabilityRangeOfFormulaBounded(ModelBase model, Formula formula, Formula terminateEarlyFormula, int bound)
		{
			ProbabilityRange probabilityRangeToReachState;

			var createModel = SafetySharpRuntimeModel.CreateExecutedModelFromFormulasCreator(model);

			var nmdpGenerator = new NmdpFromExecutableModelGenerator<SafetySharpRuntimeModel>(createModel) { Configuration = TraversalConfiguration };
			nmdpGenerator.AddFormulaToCheck(formula);
			var nmdp = nmdpGenerator.GenerateMarkovDecisionProcess(terminateEarlyFormula);


			if (_convertNmdpToMdp)
			{
				var nmdpToMpd = new NmdpToMdp(nmdp);
				var mdp = nmdpToMpd.MarkovDecisionProcess;
				using (var modelChecker = new BuiltinMdpModelChecker(mdp, System.Console.Out))
				{
					probabilityRangeToReachState = modelChecker.CalculateProbabilityRange(formula);
				}
			}
			else
			{
				using (var modelChecker = new BuiltinNmdpModelChecker(nmdp, System.Console.Out))
				{
					probabilityRangeToReachState = modelChecker.CalculateProbabilityRange(formula);
				}
			}
			return probabilityRangeToReachState;
		}

		/// <summary>
		///   Calculates the probability to reach a state whether <paramref name="stateFormula" /> holds.
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="stateFormula">The state formula which _must_ finally be true.</param>
		/// <param name="bound">The maximal number of steps. If stateFormula is satisfied the first time any step later than bound, this probability does not count into the end result.</param>
		public static ProbabilityRange CalculateProbabilityRangeToReachStateBounded(ModelBase model, Formula stateFormula, int bound)
		{
			var formula = new BoundedUnaryFormula(stateFormula, UnaryOperator.Finally, bound);
			return CalculateProbabilityRangeOfFormulaBounded(model,formula, stateFormula, bound);
		}



		/// <summary>
		///   Calculates the probability to reach a state where <paramref name="stateFormula" /> holds and on its way
		///   invariantFormula holds in every state, or more formally Pr[invariantFormula U stateFormula].
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="stateFormula">The state formula which _must_ finally be true.</param>
		/// <param name="invariantFormula">The state formulas which must hold until stateFormula is satisfied.</param>
		/// <param name="bound">The maximal number of steps. If stateFormula is satisfied the first time any step later than bound, this probability does not count into the end result.</param>
		public static ProbabilityRange CalculateProbabilityRangeToReachStateBounded(ModelBase model, Formula stateFormula, Formula invariantFormula, int bound)
		{
			var formula = new BoundedBinaryFormula(invariantFormula, BinaryOperator.Until, stateFormula, bound);

			return CalculateProbabilityRangeOfFormulaBounded(model, formula, stateFormula, bound);
		}


		/// <summary>
		///   Conduct a quantitative analysis where parameters may vary
		/// </summary>
		/// <param name="model">The model that should be checked.</param>
		/// <param name="parameter">The parameters of the parametric analysis.</param>
		public static QuantitativeParametricAnalysisResults ConductQuantitativeParametricAnalysis(ModelBase model, QuantitativeParametricAnalysisParameter parameter)
		{
			var stepSize = (parameter.To - parameter.From) / (parameter.Steps - 1);

			var sourceValues = new double[parameter.Steps];
			var resultValues = new double[parameter.Steps];

			for (var i = 0; i < parameter.Steps; i++)
			{
				var currentValue = i * stepSize;
				sourceValues[i] = currentValue;
				parameter.UpdateParameterInModel(currentValue);

				double currentResult;
				if (parameter.Bound.HasValue)
					currentResult=CalculateProbabilityToReachStateBounded(model, parameter.StateFormula, parameter.Bound.Value).Value;
				else
					currentResult = CalculateProbabilityToReachState(model, parameter.StateFormula).Value;
				System.GC.Collect();
				resultValues[i] = currentResult;

			}

			var result = new QuantitativeParametricAnalysisResults
			{
				From = parameter.From,
				To = parameter.To,
				Steps = parameter.Steps,
				SourceValues = sourceValues,
				ResultValues = resultValues
			};
			return result;
		}
	}
}